# 6주차 문자열 심화

## 대소문자 변환

In [21]:
text = "Hello, Python!" #대소문자 변환: upper, lower 함수

print(text)
print(text.upper())
print(text.lower())

Hello, Python!
HELLO, PYTHON!
hello, python!

## 공백 제거

In [22]:
name = "    python    "

print(f"원본:  '{name}'")

print(f"정리 후: '{name.strip()}'")

# 변수와 String 비교
print("공백이 있을 때 비교:", name == "Python")
print("공백 제거 후 비교:", name.strip() == "Python")

원본:  '    python    '
정리 후: 'python'
공백이 있을 때 비교: False
공백 제거 후 비교: False

# 문자열 바꾸기

In [23]:
sentence = "파이썬을 배우고 있습니다. 파이썬은 재미있습니다."

new_sentence = sentence.replace("파이썬", "Python")

print("원본:", sentence)
print("수정:", new_sentence)

원본: 파이썬을 배우고 있습니다. 파이썬은 재미있습니다.
수정: Python을 배우고 있습니다. Python은 재미있습니다.

In [24]:
price = "1,500,000원"

clean_price = price.replace(",","").replace("원","")
#replace 함수 뒤에 ""공백 따옴표를 붙이는 이유가,
#바꿀 내용은 어떻게 바꿀건지의 형태도 설정해주기 위해서

print(int(clean_price))

1500000

# 문자열 나누기 (split함수)

In [25]:
words = "사과 바나나 포도 딸기"
word_list = words.split() #띄어쓰기를 기준으로 문자열을 나누다.
print(word_list)

['사과', '바나나', '포도', '딸기']

In [26]:
words = "사과,바나나,포도,딸기"
word_list = words.split(",") #","을 기준으로 문자열을 나누다.
print(word_list), len(word_list) #문자열 갯수 세기

['사과', '바나나', '포도', '딸기']

(None, 4)

# 문자열 자르기

In [27]:
phone = "010-1234-5678"

# 앞에서 3글자
print(phone[0:3])
# 가운데 4글자
print(phone[4:8])
# 마지막 4글자
print(phone[-4:]) #같은 의미로 [9:13]

010
1234
5678

# 문제

이메일 주소에서 아이디와 도메인을 분리하세요

In [28]:
email = "12345@email.daelim.ac.kr"

parts = email.split("@")
user_id = parts[0]
domain = parts[1]

print(f"이메일:", email)
print("아이디:", user_id)
print("도메인:", domain)

이메일: 12345@email.daelim.ac.kr
아이디: 12345
도메인: email.daelim.ac.kr

# 문자열 검색

In [29]:
review = "이 제품은 정말 좋아요! 배송도 빠르고 품질도 훌륭합니다."

print("좋아요 포함:", "좋아요" in review)
print("나빠요 포함:", "나빠요" in review)

if "좋아요" in review and "훌륭" in review:
    print("긍정적 리뷰")
else:
    print("부정적 리뷰")

좋아요 포함: True
나빠요 포함: False
긍정적 리뷰

# 함수 심화

# 함수 기본값

In [30]:
def greet(name, greeting="환영합니다"):
    print(f"{name}님, {greeting}")

greet("대림대")
greet("대림대", "안녕하세요")

대림대님, 환영합니다
대림대님, 안녕하세요

In [31]:
# 할인율 계산
# discount: 0.0~1,0 할인율 적용 가능 (수치: 0% ~ 100%)
def calculate_price(price, discount=0):
    discounted = price * (1 - discount)
    return discounted

print(f"기본 가격: {calculate_price(10000)}원")
print(f"할인 가격: {calculate_price(10000, 0.1)}원")

기본 가격: 10000원
할인 가격: 9000.0원

# 함수에서 여러값 반환하기

In [32]:
# 최솟값과 최댓값을 동시 반환하는 함수

def min_max(numbers):
    minimum= min (numbers)
    maximum =max (numbers)
    return minimum, maximum

scores = [10,20,30,40,50,60,70,80]
low, high = min_max(scores)
print("최솟값:", low)
print("최댓값:", high)

최솟값: 10
최댓값: 80

## 문제
class_scores = [45,62,78,55,90,83,71,66,48,95]

1.성적 분석 함수 생성  
2. 아래와 같은 로그 출력 - 4줄
    - 평균: x.x점 (소수점 1번째 자리까지만 출력)
    - 최고점: xx점
    - 최저점: xx점
    - 합격(60점 이상) :x명

In [33]:
def numbers(number):
    sum = 0
    count_num = 0
    min_num = min(number)
    max_num = max(number)
   
    for x in number:
        sum += x
        avg_num = sum / len(number)
       
        if x >= 60:
            count_num += 1
   
    return min_num, max_num, avg_num, count_num

class_scores = [45, 62, 78, 55, 90, 83, 71, 66, 48, 95]
low, high, avg, count = numbers(class_scores)

print(f"평균 : {round(avg, 1)}점")
print(f"최고점 : {high}점")
print(f"최저점 : {low}점")
print(f"합격(60점 이상) : {count}명")

평균 : 69.3점
최고점 : 95점
최저점 : 45점
합격(60점 이상) : 7명

# Pandas 심화

In [34]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# 학생 데이터
grade_data = {
    "name": ["kim", "lee", "park", "cho", "choi", "jung"],
    "korean": [88, 72, 95, 65, 80, 91],
    "math": [75, 90, 65, 85, 77, 82],
    "english": [82, 88, 76, 70, 95, 78],
} #딕셔너리 생성

grade_df = pd.DataFrame(grade_data)
grade_df

   name  korean  math  english
0   kim      88    75       82
1   lee      72    90       88
2  park      95    65       76
3   cho      65    85       70
4  choi      80    77       95
5  jung      91    82       78

## 정렬하기

In [36]:
print("------ 국어 점수 낮은 순 ------")
print(grade_df.sort_values("korean"))
print()
print("------ 수학 점수 높은 순 ------")
print(grade_df.sort_values("math", ascending = False))

------ 국어 점수 낮은 순 ------
   name  korean  math  english
3   cho      65    85       70
1   lee      72    90       88
4  choi      80    77       95
0   kim      88    75       82
5  jung      91    82       78
2  park      95    65       76

------ 수학 점수 높은 순 ------
   name  korean  math  english
1   lee      72    90       88
3   cho      65    85       70
5  jung      91    82       78
4  choi      80    77       95
0   kim      88    75       82
2  park      95    65       76

# 새로운 열 추가하기

In [37]:
grade_df["average"] = \
    (grade_df["korean"] + \
        grade_df["math"] + \
            grade_df["english"]) / 3
grade_df["average"] = grade_df["average"].round(1)
grade_df

   name  korean  math  english  average
0   kim      88    75       82     81.7
1   lee      72    90       88     83.3
2  park      95    65       76     78.7
3   cho      65    85       70     73.3
4  choi      80    77       95     84.0
5  jung      91    82       78     83.7

In [38]:
grade_df["grade"] = grade_df["average"].apply(
    lambda x: "A" if x >= 80 else "B"
)

grade_df

   name  korean  math  english  average grade
0   kim      88    75       82     81.7     A
1   lee      72    90       88     83.3     A
2  park      95    65       76     78.7     B
3   cho      65    85       70     73.3     B
4  choi      80    77       95     84.0     A
5  jung      91    82       78     83.7     A

## 그룹별 통계

In [39]:
group_avg = grade_df.groupby("grade")["average"].mean()
print("등급별 평균:")
print(group_avg)

등급별 평균:
grade
A    83.175
B    76.000
Name: average, dtype: float64

In [40]:
# 응용 - 회사 부서별 급여 파악

employee_data = {
    "name": ["kim", "lee", "park", "cho", "choi", "jung"],
    "department": ["개발", "마케팅", "개발", "인사", "마케팅", "인사"],
    "salary": [4200, 3500, 4800, 3200, 3800, 5000]
}

emp_df = pd.DataFrame(employee_data)

#부서별 평균 급여
dept_avg = emp_df.groupby("department")["salary"].mean()
print("-----부서별 평균 급여-----")
print(dept_avg.round(0))
print()
print("-----부서별 인원 수-----")
dept_count = emp_df.groupby("department")["name"].count()
print(dept_count)

-----부서별 평균 급여-----
department
개발     4500.0
마케팅    3650.0
인사     4100.0
Name: salary, dtype: float64

-----부서별 인원 수-----
department
개발     2
마케팅    2
인사     2
Name: name, dtype: int64